### ISSUE TITLE
Make Elixir watch multiple different sass files

### ISSUE THREAD

**Issue by GiselleSerate** [aryam7/studycloud#10]
So index is theoretically compiling, but I also want to make about.css compile as well, and so forth.

**Comment by GiselleSerate** [comment]
Watch doesn't seem to be working, but it is doing multiple files.

**Comment by aryam7** [comment]
Not sure if this is important, but Laravel Elixir doesn't exist in Laravel 5.5, the version that we're using.
The new one is called [Laravel Mix](https://laravel.com/docs/5.5/mix).

**Comment by GiselleSerate** [comment]
We have bigger problems now. See Issue #13.
