### ISSUE TITLE
class tree instead of topic tree

### ISSUE THREAD

**Issue by aryam7** [aryam7/studycloud#102]
The topic tree allows for maximum flexibility when connecting topics to each other. This can lead to some crazy tree structures that involve complicated relationships between topics. This is great. It will lead to some very informative ways of organizing information on the site.

Unfortunately, the topic tree isn't without rules; there are certain relationships that shouldn't be allowed in our topic tree. For example, there can't be infinite loops in the tree, and a topic shouldn't have a child that is also one of its descendants. See #94 for a growing list of such rules.

These rules must be maintained by the site; a user shouldn't be allowed to violate any of these rules and should be made aware of them through an intuitive interface. Unfortunately, the code for both the validation logic and the interface will be complicated. In fact, I think it will be complicated enough that we actually won't be able to finish all of it by the end of the year.

It might be better to use the class tree instead of the topic tree in our MVP, since the class tree is a lot simpler. It follows a more traditional folder structure, where any given class can only have one parent. This means we won't run into the same complications we had with the topic tree. To top it off, most of the code we've already written for the topic tree can be reused for the class tree, so I don't think it would be too hard to implement it by the end of the year.

What do y'all think?

**Comment by GiselleSerate** [comment]
What does it mean to have a class be a child of another class, i.e. what is a non leaf class?

**Comment by aryam7** [comment]
Classes can be anything related to the course structuring.
An example might be "Ch 1" or "Ch 2", since these are logical subdivisions of a course.
On the other hand, "Chemistry Department" could also be a class, since courses are often organized under departments.
By contrast, topics are abstract concepts somewhat unrelated to how the class is structured in real life.

**Comment by GiselleSerate** [comment]
What if you only have a teacher attribute for each resource and allow people to see, say, what teachers are included under a certain node? It seems that if they're trying to find stuff by teacher, maybe it's not as useful if they find resources that are not for that teacher in specific. Maybe I'm not seeing it . . . what user story would that be? Like most times, you'll be looking within a class, and the teacher will be an extra filter if you wanted specifically resources for that teacher. Maybe you'd be using a teacher attribute to get a sample of what classes that teacher teaches, but I'm not sure you'd want other teachers' resources in that case.

**Comment by aryam7** [comment]
Hmmm that's a good point. Yah, I like the idea you propose: of having teachers show up under a class when resources have been organized under that class with those teachers. That seems like a good compromise.

**Comment by aryam7** [comment]
Ok.
1. Cool
2. How about we only allow resources on leaf classes for now? We can always change this later (ie after MVP).
3. Yeah, I agree with you that it should be easy to attach teachers to classes by retrieving that information from Mudd's API. But I think it's important to note that we're trying to build this site such that it can be used by many different schools, and not every school will have a convenient API.
It seems like Giselle's suggestion, that we get this information from the resources themselves, seems like a happy medium.
I'm also not sure that requiring the teacher will be all that much work. I think it can be valuable information, given that a resource might not be relevant to others in the same class if they have different teachers. Perhaps we could make a drop down (or search/dropdown/text-input thingy?) to make this easier?

As for how the class tree is created, I'm currently going on the assumption that we are allowing both user-created and automatic classes. However, the automatic classes will be non-editable (except by admins). And there will be a level in the tree below which automatic classes can't be added (and above which user-created classes can't added?). Let me know if you guys had a different idea.

**Comment by aryam7** [comment]
## Deciding which classes can be attached to resources
We mentioned before that only leaf classes should be allowed to have resources. On second thought, this seems like it may lead to some ugly consequences.
For example, what would we do when a leaf class with resources becomes a non-leaf class or a leaf class is moved higher up in the hierarchy? You can see how it might quickly become a UI nightmare.
Instead, we plan to allow resources to be attached by default to almost any class. We'll add a boolean attribute to every class that will allow us to toggle whether resources can be attached to it. When a new class is created, it will automatically be set to true, but we (the administrators) will be able to set it to false if we want.

**Comment by aryam7** [comment]
Closing this for now. It seems like all of the details of the class tree have been ironed out at this point, except for the teacher attribute (see issue #128).
