### ISSUE TITLE
single sign on

### ISSUE THREAD

**Issue by GiselleSerate** [aryam7/studycloud#115]
There's a guy you need to talk to. 
Does the persistence of the login session happen in Javascript or pure php?

**Comment by aryam7** [comment]
I don't think you'll need to worry about persisting the login session. PHP can set cookies and session data.
also relevant: [an article about google oauth](https://developers.google.com/identity/protocols/OAuth2WebServer#creatingclient)

**Comment by aryam7** [comment]
### How are we gonna store google sign in data?
- [ ] we can store fname, lname, and email in their usual spots
- [ ] we should create a new enum field indicating which provider we retrieved the account from
    ex: "google"
- [ ] we have a rememberToken field. we should store the `refresh token` in there
- [ ] password might have to be null?
    or maybe we could use it to store the regular access `token`
- [ ] how are we gonna know if they are a student or teacher?
    maybe there's a way to request that info during account creation. that would be nice b/c I don't wanna have to request it after
- [ ] unfortunately, the user's email can be changed. we should use their google id to identify them, instead.
    but where are we gonna store this info? the most flexible way would be to create a new table with oauth attribute name/value pairs associated with each user_id
