### ISSUE TITLE
Consider gitignoring all .css files

### ISSUE THREAD

**Issue by GiselleSerate** [aryam7/studycloud#12]
Do we want them in version control?

**Comment by aryam7** [comment]
Ugh. I guess not, since they're re technically generated files.
But that means everyone has to install NVM, npm, and nodejs, right?

**Comment by GiselleSerate** [comment]
Theoretically everyone has to do a bit of setup, but the less the better?

**Comment by aryam7** [comment]
I've been thinking about this some more...
It's probably better to leave them not gitignored. Mostly because our future deployment system will just pull from the repo and npm shouldn't exist on the server. But also because it will make everyone's lives a little easier
