### ISSUE TITLE
JS Binding

### ISSUE THREAD

**Issue by aryam7** [aryam7/studycloud#121]
We need to revise Server.js to make sure that Max can bind things to his callback functions. He is currently prevented from using js binding because in our code, we set his callbacks equal to properties of the Server object (and thus, remove whatever he bound to his callback)
- [x] revise Server.js so that the callbacks are passed around as arguments, instead

**Comment by Yirnauxolfa4** [comment]
So is this significantly different from the Java bind method? Bind would allow us to bind methods or variables to functions

**Comment by Yirnauxolfa4** [comment]
would we be binding data directly to the variables such as the callbacks the functions take in or to the callbacks themselves within the function?

**Comment by Yirnauxolfa4** [comment]
I guess the ultimate question is: which of the JS functions is Max specifically calling/how do they relate to the JS callbacks?

**Comment by aryam7** [comment]
A great explanation of js binding is provided [here] (https://gist.github.com/zcaceres/2a4ac91f9f42ec0ef9cd0d18e4e71262). The plan is for Max to bind data to his callback functions before he passes them to the functions in Server.js. Then, when we call his callback functions, he'll be able to access the data he bound. This is important to him because otherwise, he won't be able to know what parameters were used to call the Server.js functions.
On the Server.js side, we will only need to pass him the data that is returned from the Server. Otherwise, we can pass him the error object thingy that we get from d3.

**Comment by aryam7** [comment]
@ciennG and @Yirnauxolfa4,
It looks like you guys might have finished implementing this in ceb0d69b1585125665e7267f73fbadd27bfbe3fd? If so, would you feel comfortable opening a pull request to merge it into master?

**Comment by aryam7** [comment]
this was merged in #129
