### ISSUE TITLE
Update things to Laravel 5.5; Elixir->Mix

### ISSUE THREAD

**Issue by GiselleSerate** [aryam7/studycloud#13]
https://github.com/JeffreyWay/laravel-mix/issues/69

npm and node are apparently not supposed to be the Most updated versions because then you break things. Reportedly Laravel wants a prerelease version of npm and/or node. 

Try: 

- [ ] use yarn instead of npm
- [ ] "nuke the node_modules directory and try again"

**Comment by aryam7** [comment]
[This documentation](https://github.com/JeffreyWay/laravel-mix/tree/master/docs) might be helpful. You probably tried this already, but here are [the installation instructions](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/installation.md). Also, here's a [troubleshooting page](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/troubleshooting.md) I found. And here's [that video we were watching earlier](https://laracasts.com/series/whats-new-in-laravel-5-4/episodes/3).
Not sure if any of these resources are helpful, but I thought I'd put them here anyway.

**Comment by GiselleSerate** [comment]
Commit 2aca01982b472810941c60db29854a120af7737f resolves this to some extent; now watches sass files properly.
