### ISSUE TITLE
display server validation errors through ajax

### ISSUE THREAD

**Issue by aryam7** [aryam7/studycloud#138]
Once the AJAX team has completed the class CRUD, I think it might be a good idea for them to work with the PHP team to make sure we can pass validation errors through to the user via AJAX.

Currently, `Server.js` captures the response or error and passes it back to whoever called it. In addition to this, it might be helpful if it could return an HTTP status code and a parsing of the responseJSON from the server. This way, the code calling it can individually handle each of the different response messages that it returns. If we feel it necessary, we may also want to create a Wiki page detailing what sort of messages `Server.js` will return.

The server responses might need to be altered to make it easier for the AJAX team to parse the responseJSON. However, `Server-jQuery.js` _does_ currently return the responseJSON, indicating that perhaps `Server.js` could also do this with minimal modifications on the PHP side.

We might also want to come up with a standard for server responses so that the AJAX team can know what the server is telling it and then act accordingly. This will involve the two teams reading about which HTTP errors Laravel throws in any given situation. We may choose to make another Wiki page for this task.

**Comment by aryam7** [comment]
Here's the [Laravel documentation for validation](https://laravel.com/docs/5.5/validation#quick-writing-the-validation-logic), which discusses how it will send a responseJSON containing validation errors if the request was sent through AJAX. Oddly enough, it says that it will send a 422 HTTP status code, but experience has shown it to be a 403.

**Comment by Yirnauxolfa4** [comment]
d3 returning a 200 error when it should be returning a 422 in add resource but jQuery was able to do it
https://developers.google.com/web/updates/2015/03/introduction-to-fetch  :syntax for fetch

**Comment by aryam7** [comment]
@aryam7 consider converting custom 405 validation errors to 422, to be consistent with laravel's validation?

**Comment by ciennG** [comment]
We might just use jQuery.
Changes to make:
-update error handling
-make callbacks uniform and consistent
-Port class CRUD to jQuery
-Testing

**Comment by ciennG** [comment]
Quick quality-of-life changes to make in getData:
-don't return the promise
-make sure we don't call handleSuccess with node

**Comment by ciennG** [comment]
Also, rename treeHandleError/Success to be more general.

**Comment by aryam7** [comment]
Hey guys!
So I was looking around the internet today and stumbled upon [an article](https://benjaminlistwon.com/blog/adding-more-robust-ajax-detection-in-laravel/) that may be helpful.
According to this article, our problem with the fetch API was that we weren't sending an [X-Requested-With](https://stackoverflow.com/questions/17478731/whats-the-point-of-the-x-requested-with-header) header attribute to the server. Laravel apparently uses this attribute to figure out if the request being made is an AJAX request. jQuery apparently sends this attribute by default in every AJAX request (which is perhaps why it was working).

Let me know if this works!

**Comment by aryam7** [comment]
> 
> 
> For @aryam7
> See issue #145

@ciennG and @Yirnauxolfa4 
The reason that your getTree() and getData() functions are giving you a 302 instead of a 422 is because you aren't passing them an `X-Requested-With` header attribute. I checked recently; the server _does_ actually validate the `id`

**Comment by aryam7** [comment]
finished in #146
