### ISSUE TITLE
Move css and/or sass and/or html files to wherever they're supposed to be

### ISSUE THREAD

**Issue by GiselleSerate** [aryam7/studycloud#14]
Where does Laravel say it wants these?

**Comment by aryam7** [comment]
See [this link](https://laravel.com/docs/5.5/structure). But honestly, the sass files can be wherever we want, as long as we specify the correct directory when we write webpack.mix.js. [This page](https://laravel.com/docs/5.5/mix#sass) has some more details.
I think generated css goes in public/css.
Sass files go in resources/assets/sass/.
HTML files should be rewritten as blade.php files and placed in resources/views/. You can look at home.blade.php for an example of how to correctly include the template using blade. Or you can just get the PHP team to do it.

**Comment by aryam7** [comment]
Actually, on second thought, we might have to put sass files in resources/assets/sass instead of public/css/SCSS if we don't want them to be publicly available. I'm not sure if this really matters though. Just do whatever is your preference.
