### ISSUE TITLE
Figure out home linking

### ISSUE THREAD

**Issue by GiselleSerate** [aryam7/studycloud#23]
It's an object. Clicking on it is not working. Or maybe the blade isn't being updated on the fly I don't know

**Comment by GiselleSerate** [comment]
Problematico: 
- [ ] huge bounding box
- [ ] how do you link home, anyway?

**Comment by aryam7** [comment]
In the Code/routes/web.php file, we've defined a route for the home page:
```
Route::get('/', function () {
    return view('home');   	
});
```
This matches the address `'/'` with the home.blade.php file, so an anchor tag with `href="/"` should point you to the home page. Lemme know if that doesn't work.

**Comment by aryam7** [comment]
For posterity:
We ended up using `href="{{ routes('home') }}"`, which has blade automatically determine the URL from the named route "home"
