### ISSUE TITLE
make login/logout a module

### ISSUE THREAD

**Issue by GiselleSerate** [aryam7/studycloud#29]
so that we can easily switch it out

**Comment by aryam7** [comment]
You might also want to take a look at [what I've done](https://github.com/aryam7/studycloud/commit/f430cb8e54316bbb9929ddea1f27eb3a172ceb3d) with the login code. I had to change some of the name attributes and I added a temporary logout button. I also stuck a remember-me field in there, but it's kinda ugly right now.
Also, I changed the form to submit as POST and added a `csrf_field`. All requests sent to the server (except maybe GETs?) will need that `csrf_field`.

When we make other authentication-based pages in the future, like the registration page and whatnot, we should definitely take a look at the example HTML that Laravel gave us. You can find it in `/resources/views/auth/` and `/resources/views/passwords/`. The most important things to match up with their code are the type of request (POST, GET, etc) and the name attributes of the inputs.
Also, here's a super handy command that will show you which routes Laravel has defined for its example HTML: `php artisan route:list`.

**Comment by GiselleSerate** [comment]
This is done as of approximately a week ago.
