### ISSUE TITLE
Finish Server class

### ISSUE THREAD

**Issue by TrangQDinh** [aryam7/studycloud#40]
We wrote and tested the beginning of Server.getData, include Server.handleSuccess and handleError.

**Comment by aryam7** [comment]
![1518929219848928705895](https://user-images.githubusercontent.com/23412689/36348398-ba1fa456-1423-11e8-9e1c-b90b1ed3fc40.jpg)

**Comment by aryam7** [comment]
To test that getData is able to make a json request: run laravel and try running getData in the browser console. the code for the console is:
`test = new Server; test.getData(1, 2);`

**Comment by ciennG** [comment]
Site for d3's request functionalities:
https://github.com/d3/d3-request

**Comment by aryam7** [comment]
*** Update ***
Feiyang pushed code in commit https://github.com/aryam7/studycloud/commit/3700f2617468a571f7bcbc109d6c68fcb7ae113d
We figured out how to call handleError and handleSuccess

To do next:
- test that it works
- do some processing of the error in handleError()
- celebrate!

**Comment by ciennG** [comment]
We have a finished Server.js, but it still doesn't handle errors exactly as we might need to. In addition, we may want to do some processing in the handleSuccess function, but as far as we know, that isn't necessary.

**Comment by aryam7** [comment]
Hoorah! @Maxwellfire, can you try this out and let us know about any changes or suggestions below?
