### ISSUE TITLE
use laravel push and stack directives to move page specific <link> and <script> out of layout

### ISSUE THREAD

**Issue by aryam7** [aryam7/studycloud#8]

**Comment by aryam7** [comment]
[https://laravel.com/docs/5.4/blade#stacks] talks about this

**Comment by aryam7** [comment]
@GiselleSerate:
just double checking - is index.css for the layout? ie is it needed for every page that has the navbar, header, etc?

**Comment by GiselleSerate** [comment]
@aryam7 Yeah, I'll write more css files for specific pages but that should be the one. By the way, where did it go? I see my sass folder and a map file but index.css seems to be gone.

**Comment by aryam7** [comment]
@GiselleSerate We moved it to the public/css/ directory
https://github.com/aryam7/studycloud/commit/121ffd07c0d6d369e4049201283ed1a6b46181f0
Does that cause problems for your sass development workflow?

**Comment by GiselleSerate** [comment]
No, as long as the sass files go with it. I can move them.

**Comment by aryam7** [comment]
Cool, sounds good. I think that's fine, but from what I've seen, ppl don't usually keep their scss files in the public folder. I don't see why not, but maybe it's some sort of security issue? I'll try to read up on it, but I don't think it should be a problem right now at least.

**Comment by aryam7** [comment]
So it doesn't seem like there's a whole lot of reason for keeping scss files outside of the public directory. The one benefit, it seems, is that you adhere to some sort of standard where everything that is publicly available is only what needs to be publicly available. Maybe it's a sense of cleanliness?
Regardless, it's pretty easy to do with this thing called webpack, which is apparently another reason why it's done. (Laravel has webpack built in.)
So let's just keep them there? And if we feel the urge, it would be easy to switch.

**Comment by aryam7** [comment]
For posterity, this issue was fixed in commit https://github.com/aryam7/studycloud/commit/7beb29f32d0ea5b7c6c2bb033e7b03b247b4ad67
@GiselleSerate, if you ever want the layout to include css or javascript for a specific page, you can do it like this
