### ISSUE TITLE
two different versions of js code

### ISSUE THREAD

**Issue by aryam7** [aryam7/studycloud#81]
For some reason, the repo has two copies of the same `Server.js` file. There are a few other files that are also duplicated.
Let's get rid of the duplicates.

**Comment by aryam7** [comment]
@GiselleSerate, it seems like you added [`Server.js`](https://github.com/aryam7/studycloud/blob/master/public/js/Server.js) two months ago to the `js` folder. Do you remember why?
Did you manually copy-paste that file?

**Comment by GiselleSerate** [comment]
I haven't written or edited anything in `Server.js`. If it says I added it, it's probably just due to some Git mess that happened somewhere along the line and you can do whatever you'd like to it.
