### ISSUE TITLE
flexible URLs

### ISSUE THREAD

**Issue by aryam7** [aryam7/studycloud#84]
#### The Problem
Our blade files need to be used in many different pages. This requires that any single blade file be written such that it can adapt to work the same, no matter which page we use it in.
This is especially important when we work with URLs. Currently, we use relative paths to files (for ex: "css/_resource.css") in order to access `js` and `css` files. These paths are relative to the URL of the page that loads them, so these links will break as soon as we decide to use these blade files in a different page where the base URL for the page is a level higher or lower in the file system.

#### A Solution
An easy solution would be to just prefix each url with `/`, making them absolute instead of relative. But what if we want to move our `js` and `css` directories one day?
We should use abstraction. Laravel has a number of different helper functions for this exact type of problem. We should read up on [URL Generation](https://laravel.com/docs/5.5/urls) and the use of the global helper functions `url()`, `asset()`, and `route()`. We might also strive to understand [the differences between them](https://stackoverflow.com/questions/39217975/in-laravel-5-whats-the-difference-between-url-and-asset), so that we can recognize in which situations to use each of them.

Do y'all agree that we should use this solution? If so, can we make a pull request for fixing URLs in the current code? I think it would be as easy as just going through all of the blade files and applying the helper functions to the links.

**Comment by GiselleSerate** [comment]
### CSS links:
- [ ] about (2)
- [ ] home (2)
- [ ] layout (4)
- [ ] layout (8)
- [ ] layout (14)
- [ ] resource (7)
- [ ] topics (2)

### JS links:
- [ ] layout (9)
- [ ] layout (10)
- [ ] layout (11)
- [ ] layout (15)
- [ ] layout (16)
- [ ] layout (17)
- [ ] app (78)
- [ ] resource (11)
- [ ] topics (15)

**Comment by GiselleSerate** [comment]
Looks like this was merged in #104. Byee~
